service: hackon6-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: dev
  memorySize: 256
  timeout: 10
  environment:
    NODE_OPTIONS: --enable-source-maps
    ITEMS_TABLE: hackon6-items-dev

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
          Resource:
            - arn:aws:dynamodb:ap-south-1:*:table/hackon6-items-dev

  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS

functions:
  health:
    handler: src/handler.health
    events:
      - httpApi:
          path: /health
          method: GET

  createItem:
    handler: src/handler.createItem
    events:
      - httpApi:
          path: /items
          method: POST

  listItems:
    handler: src/handler.listItems
    events:
      - httpApi:
          path: /items
          method: GET

plugins:
  - serverless-offline
